Workaround Jenkins not answering shutdown query
Fixes:

    Function: jenkins.restart
      Result: False
     Comment: Mar 16, 2016 12:01:09 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
              SEVERE: I/O error in channel CLI connection to http://jenkins-ci-tests-50-master.lxc/
              java.io.IOException: Unexpected termination of the channel
                    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
              Caused by: java.io.EOFException
                    at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2332)
                    at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2801)
                    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:801)
                    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
                    at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
                    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
                    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)